services:
  - type: static
    name: fii-portfolio
    env: static
    buildCommand: npm ci && npm run build && npm run export
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
